#!/usr/bin/env python3

import argparse, sys
import getpass
import requests as r

parser = argparse.ArgumentParser()
parser.add_argument('--version', help='Prints the version of the tool', action='store_true')
parser.add_argument('login', help='Prompts you for your NLBKlik username/password and remembers them.')
args = parser.parse_args()

# Unfortunately, NLB's certificate is invalid, as it's not including an intermediate
# certificate from the chain. For this PoC we're skipping the validation altogether.
#
# TODO: replace with cert from https://gist.github.com/filipArena/d73026ea38df5c4bb6263b1a268723c1
# Thanks filipd!
VERIFY_SSL=False

if args.version:
	print('Version: 0.1')
elif args.login:
	username = input('Username: ')
	password = getpass.getpass('Password: ')
	s = r.Session()
	data = {"UserName": username, "Password": password, "X-Requested-With": "XMLHttpRequest"}
	login_res = s.post('https://www.nlbklik.com.mk/Account/LoginUserNamePassword', data=data, verify=VERIFY_SSL)
	print(login_res.text)
